ARG NEXT_PUBLIC_API_LOGIN
ARG NEXT_PUBLIC_FRONT_INVENTARIO
ARG NEXT_PUBLIC_FRONT_VENTAS
ARG NEXT_PUBLIC_FRONT_FACTURACION

FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV NEXT_PUBLIC_API_LOGIN=$NEXT_PUBLIC_API_LOGIN
ENV NEXT_PUBLIC_FRONT_INVENTARIO=$NEXT_PUBLIC_FRONT_INVENTARIO
ENV NEXT_PUBLIC_FRONT_VENTAS=$NEXT_PUBLIC_FRONT_VENTAS
ENV NEXT_PUBLIC_FRONT_FACTURACION=$NEXT_PUBLIC_FRONT_FACTURACION

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]